['Millwall', 'Norwich City', 'Nottingham Forest', 'Preston North End', 'Queens Park Rangers', 'Reading', 'Rotherham United', 'Sheffield Wednesday', 'Stoke City', 'Swansea City', 'Watford', 'Wycombe Wanderers'],

stadiums = {
    'Arsenal':'Emirates Stadium',
    'Aston Villa':'Villa Park',
    'Brighton & Hove Albion':'American Express Community Stadium',
    'Burnley':'Turf Moor',
    'Chelsea':'Stamford Bridge',
    'Crystal Palace':'Selhurst Park Stadium',
    'Everton':'Goodison Park',
    'Fulham':'Craven Cottage',
    'Leeds United':'Elland Road',
    'Leicester City':'King Power Stadium',
    'Liverpool':'Anfield',
    'Manchester City':'Etihad Stadium',
    'Manchester United':'Old Trafford',
    'Newcastle United':'St. James\' Park',
    'Sheffield United':'Bramall Lane',
    'Southampton':'St. Mary\'s Stadium',
    'Tottenham Hotspur':'Tottenham Hotspur Stadium',
    'West Bromwich Albion':'West Bromwich Albion Football Club',
    'West Ham United':'London Stadium',
    'Wolverhampton Wanderers':'Molineux Stadium',
    'AFC Bournemouth':'Dean Court',
    'Barnsley':'Oakwell Stadium',
    'Birmingham City':'St Andrew\'s',
    'Blackburn Rovers':'Ewood Park',
    'Brentford':'Brentford Community Stadium',
    'Bristol City':'Bristol City Stadium',
    'Cardiff City':'Cardiff City Stadium',
    'Coventry City':'Ricoh Arena',
    'Derby County':'Pride Park Stadium',
    'Huddersfield Town':'The John Smith\'s Stadium',
    'Luton Town':'Kenilworth Road',
    'Middlesbrough':'Riverside Stadium',
    'Millwall':'The Den',
    'Norwich City':'Carrow Road',
    'Nottingham Forest':'Nottingham Forest',
    'Preston North End':'Deepdale',
    'Queens Park Rangers':'Loftus Road',
    'Reading':'Madejski Stadium',
    'Rotherham United':'New York Stadium',
    'Sheffield Wednesday':'Hillsborough Stadium',
    'Stoke City':'Bet365 Stadium',
    'Swansea City':'Swansea.Com Stadium',
    'Watford':'Vicarage Road',
    'Wycombe Wanderers':'Adams Park'
}

def get_stadium(team) :
    return stadiums[team]
